### ISSUE TITLE
TypeError: template.replace is not a function

### ISSUE THREAD

**Issue by lucleray** [GoogleChromeLabs/size-plugin#18]
Hi 👋

I'm having an issue with the plugin :
```
TypeError: template.replace is not a function
```

The reason for the error is that `compiler.output.filename` is a function and not a string (https://webpack.js.org/configuration/output/#output-filename). I'm not sure how to solve it 😅

**Comment by developit** [comment]
I've added a workaround for now where it'll call `output.filename()` and pass it default chunk data (which will inevitably be incorrect, but hopefully will get a return value. I don't yet have a way to pass it the actual corresponding chunk data for a file, since the file on disk is from a previous webpack compilation and the chunk information is gone.
